### ISSUE TITLE
APK generation fails. Bug?

### ISSUE THREAD

**Issue by grafixpress** [Xtraball/SiberianCMS#325] opened 2017-06-25 13:46 UTC
BUG in 4.11.6 ? 
APK generation fails, after update.
I get the following error: 
keystore file does not exist in /var/tmp/applications/ionic/android/
There is no .pks file stored in this place for any of my apps.

Keystore files are stored in /var/apps/android/keystore
Should I update Android SDK?

**Comment by grafixpress** [comment] 2017-06-26 14:00
UPDATE
I have updated SDK and still
"Error keystore file does not exist"
The build stops halfway.
 Error log in aplication folder:
[26-Jun-2017 11:55:50 Europe/Dublin] PHP Warning: Declaration of Siberian_Layout_Email::load() should be compatible with Siberian_Layout::load($use_base) in /home/xxx/public_html/xxx/lib/Siberian/Layout/Email.php on line 167

**Comment by grafixpress** [comment] 2017-06-29 12:56
Sorry but  THIS IS A BUG.
1 all new apps are created wth wrong package names. This has worked alright before updates.
2 Each new app creates dozens of empty apps with wrong package names
2 all source files are copied in the right tmp subfolder. But the generator can´t create the .pks, or can´t store it, or stores where it can´t find it.

**Comment by Slicit** [comment] 2017-07-12 08:18
1. All new apps are created with wrong package names. This has worked alright before updates.
> If the package name is wrong, you were likely to create apps from another domain, or from the server IP, this could cause with no doubt, APK Generation to fail.
2. Each new app creates dozens of empty apps with wrong package names
> This is a bug, but not related to the APK generator
3. All source files are copied in the right tmp subfolder. But the generator can´t create the .pks, or can´t store it, or stores where it can´t find it.
> Sources generation, doesn't create any PKS, only APK Generator, and if APK generators fails it's likely that the `keytool` command is not in the right place.

Then for the keytool command, we changed the game in 4.12.0, I hope this will fix your issue if not yet fixed with support.

**Comment by grafixpress** [comment] 2017-07-12 17:37
Hi Slicit,
I was talking about APK generation, not source generation.
During APK generation a folder for each app is created.
build.gradle on line: 309 looks in this folder for the .pks
There is no such file in this folder - this is the wrong path.
Of course this is a bug.
I truly hope this will be fixed in 4.12

Best regards

**Comment by Slicit** [comment] 2017-07-13 09:34
Just saying, that it's not a bug, but rather that your server don't provide the `keytool` commands in the right place, in 4.12.0 we changed a little the way to find `keytool` path, but it's related to your server & not to Siberian, we tried to provide best effort on most of the Linux distributions, but some are using really weird configuration making us a hard work!

**Comment by Slicit** [comment] 2017-09-28 15:57
Closing du to inactivity.

**Closed by Slicit** 2017-09-28 15:57 UTC
Labels: help wanted
