### ISSUE TITLE
Code Scan Module: Hangs After Scanning

### ISSUE THREAD

**Issue by clifton11221** [Xtraball/SiberianCMS#436] opened 2017-09-18 15:04 UTC
The Code scanning module properly scans a code and gives you the result.  However, after clicking "Done" or "Copy" after the scan, simply hangs after that.  It says, "Loading, Please wait..." and never leaves that screen.

I'm using MAE v4.12.11.  The problem existed in MAE v4.12.10 as well.

**Comment by Slicit** [comment] 2017-09-20 15:47
Can you try with another layout ? (and what layout are you using actually ?)

**Comment by LikoV2** [comment] 2018-02-01 14:05
Can't reproduce, closing.

**Closed by LikoV2** 2018-02-01 14:05 UTC
Labels: support
