### ISSUE TITLE
M-Commerce Stopped Working

### ISSUE THREAD

**Issue by bluesnap-rock** [Xtraball/SiberianCMS#417] opened 2017-08-31 18:33 UTC
**URGENT**
Orders not going through, m-commerce broken, Its not letting you go on to select delivery type - just goes back to home page. Only recent change made is installing Progressive Loyalty. v4.12.9

**Comment by clifton11221** [comment] 2017-09-01 19:45
I doubt that it's the cause but if you remove the Progressive Loyalty does it work properly?

**Comment by bluesnap-rock** [comment] 2017-09-01 22:16
No idea how to uninstall a module?...but all APPS with MCommerce are not working. Was trying to check if same on Siberian Demo but their server is down. Just isnt getting to select payment type. Thanks.

**Comment by Slicit** [comment] 2017-09-14 10:03
This issue should be fixed in 4.12.10, probably due to Layout 9

**Closed by Slicit** 2017-09-14 10:03 UTC
Labels: support
