### ISSUE TITLE
Loyalty Card Temporary Blocking

### ISSUE THREAD

**Issue by Kaharian** [Xtraball/SiberianCMS#130] opened 2017-01-24 06:25 UTC
Hi team, I made a sample Loyalty Card and I purposely keyed in wrong pins to see what will happen... so as I was expecting, the system warns that after 3 tries card will be locked. So after 3 tries, indeed the card got locked but there was a promise that the lock is temporary and that it will be okay again after 24 hours... but no about 2 weeks after, card is still locked...

At the editor, I don't see any options to turn it back on for the specific user... and I thought it should be automatic. I hope we can fix this bug.

![card blocked](https://cloud.githubusercontent.com/assets/25316236/22236492/ff39d9c0-e216-11e6-9cfd-9c56ab89560d.jpg)

**Comment by dbyzero** [comment] 2017-01-24 10:41
Looks like a bug specific to your Siberian CMS, please create a ticket or contact contact@siberiancms.com.

**Comment by herobe** [comment] 2017-01-24 14:59
You can alter the database value. loyalty card customer. locked change from 1 to 0. I think.

**Comment by fouineux** [comment] 2017-01-24 16:55
After some tests, all seems to work fine here!

If you want to unlock your card from database, you should put the "number_of_error" field to 0 in the "loyalty_card_customer" table, and change the field "last_error". Those are the only two fields used to determine if the card is locked or not.

**Comment by Kaharian** [comment] 2017-01-24 17:30
Hi, it did nothing on my part... It still a bug. I don't know if you got it clearly... The issue here is that every 3 wrong pin tries the Card will get locked temporarily...

And then the Siberian system has designed a pop up system where it is promising that the block is temporary and that it will be reactivated after 24 hours...

The issue here is that it doesn't and it never happens... 14  x 24 hours have passed and it is still blocked.

If Siberian system creates a pop up promise like that (24 hours) the program should continue... meaning it should AUTOMATICALLY revert the card to its normal state and be working properly again.

It is not advisable to have the admin manually reverting each temporarily blocked loyalty card... Just imagine if there are thousands of card to reactivate everyday... it's a nightmare if you will think really deeply about it.

You have to put back the BUG again because this is really a bug or at least a program that is not finished until the end...

**Comment by herobe** [comment] 2017-01-24 17:53
do you have the crons running properly ?

**Comment by Kaharian** [comment] 2017-01-24 18:05
Yes I do have... Notifications are fine and the others...

**Comment by dbyzero** [comment] 2017-01-25 07:49
We cannot fix something that we cannot reproduct. Please contact support with your server information. Then dev team will check what is going wrong.

**Comment by fouineux** [comment] 2017-01-25 14:25
Actually, i finally manage to reproduce this bug, it is an issue with the server locale. A global patch will be released soon.

Thanks for your report and patience.

**Closed by fouineux** 2017-01-25 14:25 UTC
Labels: bug

**Comment by MrPatrickHenry** [comment] 2017-11-08 16:50
I am still getting this issue only fix i haveis manual set in the admin user to acces feature lock
